# Generated by Django 6.1 on 2026-08-13 19:50

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_abonnement', models.DecimalField(decimal_places=0, default=5000, max_digits=10, verbose_name="Montant de l'abonnement (XOF)")),
                ('duree_abonnement_jours', models.PositiveIntegerField(default=30, verbose_name="Durée de l'abonnement (jours)")),
            ],
            options={
                'verbose_name': 'Configuration de la plateforme',
                'verbose_name_plural': 'Configuration de la plateforme',
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('CINETPAY', 'CinetPay (carte bancaire / mobile money agrégé)')], max_length=20, unique=True)),
                ('actif', models.BooleanField(default=True, help_text="Si décoché, ce moyen de paiement est indisponible partout, même s'il est activé par un organisateur.", verbose_name='Actif sur la plateforme')),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement (plateforme)',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='devise',
            field=models.CharField(default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='est_payant',
            field=models.BooleanField(default=False, help_text='Si coché, les participants doivent régler un paiement avant que leur inscription soit confirmée.', verbose_name='Événement/formation payant(e)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Montant à régler par participant (en XOF). Requis si l'événement est payant.", max_digits=10, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', "En attente de confirmation d'email"), ('EMAIL_CONFIRME', 'Email confirmé, en attente de paiement'), ('CONFIRMEE', 'Confirmée'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=14),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True, verbose_name='Texte')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='events.evenement', verbose_name='Événement lié (facultatif)')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PublicationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo')], max_length=5)),
                ('fichier', models.FileField(upload_to=events.models.chemin_media_publication)),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='events.publication')),
            ],
            options={
                'verbose_name': 'Média de publication',
                'verbose_name_plural': 'Médias de publication',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompteReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reception', models.CharField(blank=True, help_text='Numéro mobile money qui recevra les paiements. Inutile pour CinetPay.', max_length=30, verbose_name='Numéro de réception')),
                ('nom_beneficiaire', models.CharField(blank=True, help_text="Nom affiché au payeur pour qu'il vérifie le destinataire avant d'envoyer l'argent.", max_length=150, verbose_name='Nom du titulaire')),
                ('actif', models.BooleanField(default=True, verbose_name='Activé')),
                ('proprietaire', models.ForeignKey(blank=True, help_text='Laisser vide pour le compte de la plateforme (réception des abonnements).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_reception', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
                ('moyen_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_reception', to='events.moyenpaiement')),
            ],
            options={
                'verbose_name': 'Compte de réception',
                'verbose_name_plural': 'Comptes de réception',
                'ordering': ['moyen_paiement__code'],
                'constraints': [models.UniqueConstraint(fields=('proprietaire', 'moyen_paiement'), name='unique_moyen_par_proprietaire')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('ABONNEMENT', 'Abonnement organisateur'), ('INSCRIPTION', 'Inscription à un événement/formation')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente (moyen non encore choisi)'), ('EN_ATTENTE_VALIDATION', 'Preuve envoyée, en attente de validation'), ('EN_ATTENTE_CINETPAY', 'En attente de retour CinetPay'), ('VALIDE', 'Payé et validé'), ('REFUSE', 'Refusé'), ('ECHEC', 'Échec / annulé')], default='EN_ATTENTE', max_length=25)),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to=events.models.chemin_preuve_paiement, verbose_name="Capture d'écran du paiement")),
                ('numero_expediteur', models.CharField(blank=True, max_length=30, verbose_name='Numéro utilisé pour payer')),
                ('reference_saisie', models.CharField(blank=True, max_length=100, verbose_name='Référence de la transaction (facultatif)')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.CharField(blank=True, max_length=255)),
                ('cinetpay_transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cinetpay_payment_token', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='events.abonnement')),
                ('beneficiaire', models.ForeignKey(blank=True, help_text="Organisateur qui reçoit le paiement d'inscription. Vide pour un abonnement (reçu par la plateforme).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_recus', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='events.inscription')),
                ('moyen_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='events.moyenpaiement')),
                ('payeur', models.ForeignKey(blank=True, help_text="Rempli pour un abonnement (l'organisateur qui paie). Vide pour une inscription (visiteur non authentifié).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('inscription__isnull', True), ('type_paiement', 'ABONNEMENT')), models.Q(('abonnement__isnull', True), ('type_paiement', 'INSCRIPTION')), _connector='OR'), name='paiement_lie_a_un_seul_objet')],
            },
        ),
    ]
