# Generated by Django 6.0.3 on 2026-08-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_configurationplateforme_moyenpaiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='code',
            field=models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('CINETPAY', 'CinetPay (carte bancaire / mobile money agrégé)')], max_length=20, unique=True),
        ),
    ]